spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:product_db}

# API document setting
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: order-service
    server: http://localhost:${server.port}
    title: Order service
    version: 1.0.0

aws:
  region: us-west-2
  dynamodb:
    endpoint: http://localhost:8000
