server:
  port: 4953

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: # điều hướng request đến service tương ứng thông qua chỉ định trên url
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/** # chỉ định url có chứa ký tự /auth
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment} # thay thế ký tự /auth/ thành /
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/account/** # chỉ định url có chứa ký tự /account
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment} # thay thế ký tự /account/ thành /
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/** # chỉ định url có chứa ký tự /product
          filters:
            - RewritePath=/product/(?<segment>.*), /product/$\{segment} # thay thế ký tự /product/ thành /
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/** # chỉ định url có chứa ký tự /order
          filters:
            - RewritePath=/order/(?<segment>.*), /order/$\{segment} # thay thế ký tự /order/ thành /
        - id: inventory-service
          uri: http://localhost:8086
          predicates:
            - Path=/inventory/** # chỉ định url có chứa ký tự /inventory
          filters:
            - RewritePath=/inventory/(?<segment>.*), /inventory/$\{segment} # thay thế ký tự /inventory/ thành /
        - id: mail-service
          uri: http://localhost:8087
          predicates:
            - Path=/mail/** # chỉ định url có chứa ký tự /mail
          filters:
            - RewritePath=/mail/(?<segment>.*), /mail/$\{segment} # thay thế ký tự /mail/ thành /


management: # cho phép hiển thị thông tin sức khoẻ của service
  endpoints:
    web:
      exposure:
        include: '*'
