spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes: # điều hướng request đến service tương ứng thông qua chỉ định trên url
        - id: authentication-service
          uri: http://auth-auth-chart:8081
          predicates:
            - Path=/auth/**, /v3/api-docs/authentication-service
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment} # thay thế ký tự /auth/ thành /
            - ApiRequestFilter
        - id: account-service
          uri: http://account-account-chart:8082
          predicates:
            - Path=/account/**, /v3/api-docs/account-service
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment} # thay thế ký tự /account/ thành /
            - ApiRequestFilter
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**, /v3/api-docs/product-service
          filters:
            - RewritePath=/product/(?<segment>.*), /$\{segment} # thay thế ký tự /product/ thành /
            - ApiRequestFilter
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/**, /v3/api-docs/order-service
          filters:
            - RewritePath=/order/(?<segment>.*), /order/$\{segment} # thay thế ký tự /order/ thành /
        - id: inventory-service
          uri: http://localhost:8086
          predicates:
            - Path=/inventory/**, /v3/api-docs/inventory-service
          filters:
            - RewritePath=/inventory/(?<segment>.*), /inventory/$\{segment} # thay thế ký tự /inventory/ thành /
        - id: mail-service
          uri: http://localhost:8087
          predicates:
            - Path=/mail/**, /v3/api-docs/mail-service
          filters:
            - RewritePath=/mail/(?<segment>.*), /mail/$\{segment} # thay thế ký tự /mail/ thành /
            - ApiRequestFilter

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

redis:
  host: ${REDIS_HOST:DUMMY-HOST}
  port: ${REDIS_PORT:DUMMY-PORT}

grpc:
  client:
    verify-token-service:
      address: static://auth-auth-chart:9091
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext