spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: account-service
    server: ${HOST_NAME:http://localhost}:4953/account
    title: Account service
    version: 1.0.0

grpc:
  client:
    hello-service:
      address: localhost:9091
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext