server:
  port: 8081

spring:
  application:
    name: authentication-service
  jackson.serialization.indent_output: true

management: # cho phép hiển thị thông tin sức khoẻ của service
  endpoints:
    web:
      exposure:
        include: '*'
