server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: ${EUREKA_USER:-admin}
      password: ${EUREKA_PASSWORD:-password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
